version: "3"

volumes:
  pg_data:

services:
  postgres:
    image: postgres:latest
    ports:
      - 5543:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
