name: Python package

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: "pip"
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -e .[dev]
      - name: Lint with pylint
        run: pylint --disable=C0115,C0116,C0104,C0114,W0511 src tests
      - name: Check with flake8
        run: flake8
      - name: Check import sorting
        run: isort --check-only -p savage -p tests .
      - name: Check black formatting
        run: black --check --exclude=$(VENV_DIR) --line-length=100 .
